Edits across buildpack to use latest tooling
paketo-community/cpython pull request #165
Opened 2021-03-25 21:01 UTC by sophiewigmore

- Remove hardcoded buildpack IDs/names in integration tests
- Update `README.md` to be consistent with pip rewrite README style
- Update some GoDoc
- Remove plan_entry_resolver.go and log_emitter.go
- Use occam serve matcher

2021-03-25 21:23 UTC, arjun024 requested changes

2021-03-25 21:23 UTC, arjun024 commented on detect.go
> +// Detect always passes, and will contribute a Build Plan that provides cpython.
Can we remove the always pass claim? It will error if buildpack.yml/env-variable parser fails.

2021-03-25 21:23 UTC, arjun024 commented on integration/layer_reuse_test.go
> +				MatchRegexp(`    Selected CPython version \(using <unknown>\): \d+\.\d+\.\d+`),
Can you revert this given that this buildpack only provides Python3?

2021-03-25 21:23 UTC, arjun024 commented on integration/layer_reuse_test.go
> +				MatchRegexp(`    Installing CPython \d+\.\d+\.\d+`),
Since you have added a buildpack.yml to set a particular version constraint, can you assert that the expected version version is installed?

2021-03-25 21:23 UTC, arjun024 commented on integration/layer_reuse_test.go
> +				MatchRegexp(`    Selected CPython version \(using buildpack.yml\): \d+\.\d+\.\d+`),
can you assert that the expected version?

2021-03-26 14:40 UTC, sophiewigmore commented on detect.go
> +// Detect always passes, and will contribute a Build Plan that provides cpython.
yup

2021-03-26 14:44 UTC, sophiewigmore commented on detect.go
> +// Detect always passes, and will contribute a Build Plan that provides cpython.
That's only if someone gives you a bad buildpack.yml though. From an API point of view I meant to express that nothing is needed special is needed in your app to get this to pass detection (i.e. you don't need like a requirements.txt or something)

2021-03-26 14:45 UTC, sophiewigmore commented on detect.go
> +// Detect always passes, and will contribute a Build Plan that provides cpython.
Do you see what I mean? I can take it out if you feel strongly

2021-03-26 14:53 UTC, sophiewigmore commented on integration/layer_reuse_test.go
> +				MatchRegexp(`    Selected CPython version \(using buildpack.yml\): \d+\.\d+\.\d+`),
On line 167, I am overwriting the buildpack.yml to use `buildpackInfo.Metadata.Dependencies[2].Version`, so that when the versions that we support change we don't have to change our expectations. And then for the second rebuild we overwrite the version with `buildpackInfo.Metadata.Dependencies[0].Version`.

I think the important part of this test is that something changes and that we check that a rebuild happens, not that we see the specific version that is passed in the buildpack.yml.

2021-03-26 14:55 UTC, sophiewigmore commented on integration/layer_reuse_test.go
> +				MatchRegexp(`    Selected CPython version \(using buildpack.yml\): \d+\.\d+\.\d+`),
For the `buildpack_yml_test.go` integration test, I still don't even think we can assert the exact version since it will change

2021-03-26 14:56 UTC, sophiewigmore commented on integration/layer_reuse_test.go
> +				MatchRegexp(`    Installing CPython \d+\.\d+\.\d+`),
See comment below

2021-03-26 15:17 UTC, arjun024 approved these changes

2021-03-26 15:17 UTC, merged